version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    ports:
      - 9200:9200
    networks:
      es_net:
        aliases:
          - elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    volumes:
      - ./logstash-conf:/config-dir
      - ./logstash-input:/log-input
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      es_net:
    environment:
      - dmaap_base_url=http://localhost:3904/
      - dmaap_user=user
      - dmaap_password=password
      - dmaap_consumer_group=CG42
      - dmaap_consumer_id=C42
      - event_topic=EVENT_TOPIC
      - notification_topic=NOTIFICATION_TOPIC
      - request_topic=REQUEST_TOPIC
      - elasticsearch_hosts=elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      es_net:

  backup:
    image: taskrabbit/elasticsearch-dump
    depends_on:
      - elasticsearch
    command:
      - --input=http://elasticsearch:9200/.kibana
      - --output=/backups/backup.json
      - --type=data
    volumes:
      - ./es_backup/:/backups/
    networks:
      es_net:

  restore:
    image: taskrabbit/elasticsearch-dump
    depends_on:
      - elasticsearch
    command:
      - --output=http://elasticsearch:9200/.kibana
      - --input=/backups/backup.json
      - --type=data
    volumes:
      - ./es_backup/:/backups/
    networks:
      es_net:

  default:
    image: taskrabbit/elasticsearch-dump
    depends_on:
      - elasticsearch
    command:
      - --output=http://elasticsearch:9200/.kibana
      - --input=/backups/default.json
      - --type=data
    volumes:
      - ./es_backup/:/backups/
    networks:
      es_net:


networks:
  es_net:
