FROM  docker.elastic.co/kibana/kibana-oss:6.1.3

MAINTAINER "The Onap Team"
LABEL Description="Kibana image with saved objects loading"
USER root
RUN yum install -y python-requests && yum clean all

# You can share volume to restore a default kibana configuration
RUN mkdir /saved-objects/

USER kibana


ADD startup.sh /usr/local/bin/startup.sh
ADD restore.py /usr/local/bin/restore.py
ADD backup.py /usr/local/bin/backup.py
CMD /usr/local/bin/startup.sh
    
