---
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
server.ssl.enabled: true
server.ssl.key: /usr/share/kibana/config/keystore/org.onap.clamp.key.pem
server.ssl.certificate: /usr/share/kibana/config/keystore/org.onap.clamp.crt.pem

## Search Guard
#
xpack.security.enabled: false
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver

searchguard.cookie.password: 123567818187654rwrwfsfshdhdhtegdhfzftdhncn